language: node_js

sudo: required

node_js:
  - "8.9.4"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_install:
  - export CXX="g++-4.8"
  - npm install -g npm@latest
  - npm install -g ganache-cli@latest truffle@latest
  - npm install -g codecov

install:
  - npm install

before_script:
  - ./start_rpc.sh > testrpc.log &
script:
  - sleep 5
  - truffle test
after_script:
  - npm run coverage && cat coverage/lcov.info
  - codecov